"""
app/models/recommendation.py — ContentRecommendation model.

Represents a content recommendation generated by Agent 3 for a specific
query where the target domain was not visible.
"""

import uuid
from datetime import datetime, timezone

from app.extensions import db


class ContentRecommendation(db.Model):
    __tablename__ = "content_recommendations"

    uuid = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    # Foreign keys
    profile_uuid = db.Column(
        db.String(36), db.ForeignKey("business_profiles.uuid"), nullable=False, index=True
    )
    query_uuid = db.Column(
        db.String(36), db.ForeignKey("discovered_queries.uuid"), nullable=False, index=True
    )

    # Content type: blog_post | landing_page | faq | comparison | case_study
    content_type = db.Column(db.String(100), nullable=False)

    # Suggested content title
    title = db.Column(db.String(500), nullable=False)

    # Why this content addresses the visibility gap
    rationale = db.Column(db.Text, nullable=False)

    # List of target keywords/topics (stored as JSON array)
    target_keywords = db.Column(db.JSON, nullable=False, default=list)

    # Priority: high | medium | low
    priority = db.Column(db.String(20), nullable=False, default="medium")

    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict:
        return {
            "recommendation_uuid": self.uuid,
            "profile_uuid": self.profile_uuid,
            "target_query_uuid": self.query_uuid,
            "content_type": self.content_type,
            "title": self.title,
            "rationale": self.rationale,
            "target_keywords": self.target_keywords or [],
            "priority": self.priority,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return f"<ContentRecommendation '{self.title[:40]}...'>"
